export const INTENT_TYPES = {
  ATOMIC: 'ATOMIC',
  FLOW: 'FLOW',
};

export const AI_AGENTS = {
  SCHEDULER: 'schedulerAgent',
  SERVICE: 'serviceAgent',
  SUPPORT: 'supportAgent',
  PRODUCT: 'productAgent',
};

export const SYSTEM_INTENTS = {
  WELCOME: 'WELCOME',
  GENERAL_INFORMATION: 'GENERAL_INFORMATION',
  BUSINESS_HOURS: 'BUSINESS_HOURS',
  BUSINESS_LOCATIONS: 'BUSINESS_LOCATIONS',
  BUSINESS_SERVICES: 'BUSINESS_SERVICES',
  SCHEDULING: 'SCHEDULING',
  BUSINESS_PRODUCTS: 'BUSINESS_PRODUCTS',
  UNKNOWN: 'UNKNOWN',
};

export const INITIAL_INTENT = SYSTEM_INTENTS.WELCOME;
