export const FIRESTORE = Symbol('FIRESTORE');
export const FIREBASE_ADMIN = Symbol('FIREBASE_ADMIN');
export const BUSINESS_REPOSITORY = Symbol('BUSINESS_REPOSITORY');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');

export const FIRESTORE_COLLECTIONS = {
  BUSINESS_COLLECTION: Symbol('BUSINESS_COLLECTION'),
  SESSION_COLLECTION: Symbol('SESSION_COLLECTION'),
};
